### PR TITLE
fix: rustc can't prove Send on futures returned by contract methods

### PR DESCRIPTION
**Pull request by Salka1988**

### CODE REVIEW

**Comment by digorithm** [comment]
Could you write a better title and description for this PR, please? 🙏

**Comment by Salka1988** [comment]
> Could you write a better title and description for this PR, please? pray

**Review by hal3e — APPROVED** [review]
Awesome! LGTM

**Review by MujkicA — APPROVED** [review]

**Review by digorithm — APPROVED** [review]
Haha, I love the simplicity of this 😂

**Pull request closed without merging**
