### PR TITLE
ci: add beta releasy to fuels-rs to track fuel-core

### PR DESCRIPTION
**Pull request by kayagokalp**
## Description

This PR adds beta version of `releasy` which will create `upgrade/fuel-core` branch and track changes happening in the fuel-core. This way any commits that merged to fuel-core which will be breaking fuels-rs once released, will be catched by the CI of that branch. 

This is for testing, we will install this to all repos once we are sure that everything works nicely.

### Checklist
- [ ] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary labels.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by kayagokalp** [comment]
I am not sure why the CI is failing. Any ideas?

**Comment by kayagokalp** [comment]
cc @digorithm

**Comment by digorithm** [comment]
It seems like the CI is passing 🤔

**Comment by Voxelot** [comment]
failing again because sway changed the installation page to "getting-started": https://github.com/FuelLabs/sway/commit/98d0810facc2030bc208daadd68b89b3c3d4be89

**Comment by kayagokalp** [comment]
Looks like ci is passing again

**Review by hal3e — APPROVED** [review]

**Review by xgreenx — APPROVED** [review]

**Review by Br1ght0ne — APPROVED** [review]

**Pull request merged**
