### PR TITLE
Test logging generics

### LINKED ISSUE #603: Remove --generate-logged-types flag from build script
We should remove the `--generate-logged-types` from our test projects build script once a new forc version is released. See: https://github.com/FuelLabs/sway/issues/2745

### PR DESCRIPTION
**Pull request by MujkicA**
Closes #603

Logging types with generics seems to work just fine, no further changes to the implementation were needed.

This PR just adds a new test case that calls `logs_with_type` on  generics with up to 3 levels of nesting.  It also extends the `fetch_logs` test with a generic type.

### CODE REVIEW

**Review by hal3e — COMMENTED** [review]
LGTM

**Review by iqdecay — DISMISSED** [review]
LGTM

**Comment by mohammadfawaz** [comment]
If no changes are necessary, then I can remove the flag immediately and make a new release. You can then remove the flag from the tests :)

**Comment by MujkicA** [comment]
> If no changes are necessary, then I can remove the flag immediately and make a new release. You can then remove the flag from the tests :)

Yup, no changes needed. I would remove the flag in this PR then 😄

**Review by digorithm — DISMISSED** [review]
Nice!

**Review by segfault-magnet — APPROVED** [review]

**Pull request merged**
