### PR TITLE
chore: add test for trig never

### LINKED ISSUE #1197: Manual block production with Trigger::Never leads to error
Using `Trigger::Never` with manual block production leads to the following error: 

`Error: IOError(Custom { kind: Other, error: "Response errors; unable to produce blocks without a consensus key" })`

I've tried setting `consensus: ConsensusConfig::default_poa()` inside the call to `ChainConfig::local_testnet()` and verifying the signing key is actually set but the error still persists. 

Repro:
```rust
async fn test_trig_never() -> Result<()> {
    let config = Config {
        block_production: Trigger::Never,
        ..Config::default()
    };
    let wallets =
        launch_custom_provider_and_get_wallets(WalletsConfig::default(), Some(config), None)
            .await?;
    let wallet = &wallets[0];
    let provider = wallet.try_provider()?;

    let inputs = wallet
        .get_asset_inputs_for_amount(BASE_ASSET_ID, 100)
        .await?;
    let outputs =
        wallet.get_asset_outputs_for_amount(&Bech32Address::default(), BASE_ASSET_ID, 100);

    let mut tb = ScriptTransactionBuilder::prepare_transfer(
        inputs,
        outputs,
        TxPolicies::default(),
    );
    tb.add_signer(wallet.clone());
    let tx = tb.build(&provider).await?;

    provider.send_transaction(tx).await?;
    provider.produce_blocks(1, None).await?;

    Ok(())
}
```

### PR DESCRIPTION
**Pull request by MujkicA**
Closes #1197

Blocked until https://github.com/FuelLabs/fuel-core/pull/1614 is included in a release. 

### Checklist
- [x] I have linked to any relevant issues.
- [ ] I have updated the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by digorithm — APPROVED** [review]
LGTM -- CI failing though

**Comment by MujkicA** [comment]
> LGTM -- CI failing though
The core update will solve that

**Comment by segfault-magnet** [comment]
@MujkicA this doesn't seem ready for merging. Can we convert this to a draft until the updates in core are propagated?

**Review by hal3e — APPROVED** [review]
LGTM

**Review by Salka1988 — APPROVED** [review]

**Pull request merged**
