### PR TITLE
test: add option to run against live node

### PR DESCRIPTION
**Pull request by iqdecay**
This PR adds a `cargo` feature called `test-against-live-node`, which enables running some test against a testnet node.

- This PR **does not** add the CI step, as it is still faulty with some weird errors of `status not found for transaction` (see https://github.com/FuelLabs/fuels-rs/actions/runs/6881505027/job/18718373777). These errors are being investigated as part of #1188.
- From comments on this PR, final design is this one:
If you want a test to be able to be run against a live node, remove the `Wallets` command from the `setup_test_program`, and in place use the `maybe_live_wallet` helper, as follows: 
```rust
    let [wallet]: [WalletUnlocked; 1] = maybe_live_wallet(1)
        .await?
        .try_into()
        .expect("Vec can be converted to an array");
    setup_program_test!(
        Abigen(Contract(
            name = "TestContract",
            project = "packages/fuels/tests/contracts/contract_test"
        )),
        Deploy(
            name = "contract_instance",
            contract = "TestContract",
            wallet = "wallet"
        ),
    );
```

Previously, this would have looked like this:
```rust
    setup_program_test!(
        Wallets("wallet"),
        Abigen(Contract(
            name = "TestContract",
            project = "packages/fuels/tests/contracts/contract_test"
        )),
        Deploy(
            name = "contract_instance",
            contract = "TestContract",
            wallet = "wallet"
        ),
    );
```

- This makes the code a little wordy but it's better than having to write the same tests twice. 
- I added a helper that generates up to 3 wallets connected to a testnet live node. The secret keys to these wallets are stored in github secrets.

### CODE REVIEW

**Review by hal3e — CHANGES_REQUESTED** [review]
Thanks for the devx improvement!

I have made some comments below on the current implementation. While I was testing it locally, I made a lot small changes so I added it to another branch. In the branch, `RunOnLiveNode` can be used without arguments and only one time etc. Branch: `hal3e/test-against-live-node`

Maybe it is worth to explore another implementation possibility. We could avoid adding a new command and instead rely on `env` variables. If the variable is set we can use beta wallets. So instead of checking if the command was used we could just use something like `option_env!` https://doc.rust-lang.org/stable/std/macro.option_env.html

Pseudo code:
in `code_gen`:
- check if `RUN_ON_LIVE_NODE` env variable is `Some("true")` -> use beta wallets
- else use random wallets

**Comment by hal3e** [comment]
> @hal3e thanks a lot for your suggestion! I really like the idea of environment variables. However, we want to give the option to run only some relevant tests on the live nodes, first of all because it's slower, and potentially expensive. The env variables approach does not allow for this flexibility, as the pseudocode you wrote would apply each time we call `setup_program_test` which occurs >100 times in the codebase.
> 
> Thanks a lot for the branch, it's much better this way!

That is a good point!

**Review by segfault-magnet — COMMENTED** [review]
Cleanly done!

I have one worry that I'd like to talk about:
`setup_program_test` besides being useful to us, is also marketed to users to help them bootstrap their tests quicker.

`RunOnLiveNode` isn't very flexible:
1. You cannot say where the node is live at, an old beta? Some custom user node/network?
2. It complicates the `Wallets` command. Previously it meant: "if a wallet is mentioned here I will setup the node and fund the wallet". Now it has a spin of "but if it is a live node, I will read ENV variables with some predetermined name format and connect to beta 4". 

Currently, the following is possible without changes to the code:

User connecting to a node of his choice, with wallets of his choice:
```rust
    let provider = Provider::connect("my.provider.com").await?;
    let wallet = WalletUnlocked::new_from_private_key("private_key".parse().unwrap(), Some(provider))

    setup_program_test!(
        Abigen(Contract(
            name = "TestContract",
            project = "packages/fuels/tests/contracts/contract_test"
        )),
        Deploy(
            name = "contract_instance",
            contract = "TestContract",
            wallet = "wallet"
        ),
    );
```

Us having a helper controlled by a feature:
```rust
async fn maybe_live_wallet() -> Result<WalletUnlocked> {
    if cfg!(feature = "live") {
        let provider = Provider::connect("my.provider.com").await?;
        Ok(WalletUnlocked::new_from_private_key(
            "private_key".parse().unwrap(),
            Some(provider),
        ))
    } else {
        launch_provider_and_get_wallet().await
    }
}

#[tokio::test]
async fn some_test() -> Result<()> {
    let wallet = maybe_live_wallet().await?;
    setup_program_test!(
        Abigen(Contract(
            name = "TestContract",
            project = "packages/fuels/tests/contracts/contract_test"
        )),
        Deploy(
            name = "contract_instance",
            contract = "TestContract",
            wallet = "wallet"
        ),
    );
```

This way we can keep complexity out of the macro while still being able to achieve our live tests with one extra line.

**Comment by hal3e** [comment]
> Cleanly done!
> 
> I have one worry that I'd like to talk about: `setup_program_test` besides being useful to us, is also marketed to users to help them bootstrap their tests quicker.
> 
> `RunOnLiveNode` isn't very flexible:
> 
>     1. You cannot say where the node is live at, an old beta? Some custom user node/network?
> 
>     2. It complicates the `Wallets` command. Previously it meant: "if a wallet is mentioned here I will setup the node and fund the wallet". Now it has a spin of "but if it is a live node, I will read ENV variables with some predetermined name format and connect to beta 4".
> 
> 
> Currently, the following is possible without changes to the code:
> 
> User connecting to a node of his choice, with wallets of his choice:
> 
> ```rust
>     let provider = Provider::connect("my.provider.com").await?;
>     let wallet = WalletUnlocked::new_from_private_key("private_key".parse().unwrap(), Some(provider))
> 
>     setup_program_test!(
>         Abigen(Contract(
>             name = "TestContract",
>             project = "packages/fuels/tests/contracts/contract_test"
>         )),
>         Deploy(
>             name = "contract_instance",
>             contract = "TestContract",
>             wallet = "wallet"
>         ),
>     );
> ```
> 
> Us having a helper controlled by a feature:
> 
> ```rust
> async fn maybe_live_wallet() -> Result<WalletUnlocked> {
>     if cfg!(feature = "live") {
>         let provider = Provider::connect("my.provider.com").await?;
>         Ok(WalletUnlocked::new_from_private_key(
>             "private_key".parse().unwrap(),
>             Some(provider),
>         ))
>     } else {
>         launch_provider_and_get_wallet().await
>     }
> }
> 
> #[tokio::test]
> async fn some_test() -> Result<()> {
>     let wallet = maybe_live_wallet().await?;
>     setup_program_test!(
>         Abigen(Contract(
>             name = "TestContract",
>             project = "packages/fuels/tests/contracts/contract_test"
>         )),
>         Deploy(
>             name = "contract_instance",
>             contract = "TestContract",
>             wallet = "wallet"
>         ),
>     );
> ```
> 
> This way we can keep complexity out of the macro while still being able to achieve our live tests with one extra line.

I like this approach. As this is for our CI test only, a helper controlled with a flag seems to be the best solution.

**Pull request closed without merging**
