### PR TITLE
fix: string in array parsing

### PR DESCRIPTION
**Pull request by hal3e**
closes: https://github.com/FuelLabs/fuels-rs/issues/505

There was a bug in the parsing logic of arrays and strings.
I have taken the test_project created by @QuinnLee and removed the part with primitive types inside arrays, as we have tested them already.

### CODE REVIEW

**Comment by QuinnLee** [comment]
The memory flow issue might be a compiler issue.  I created it https://github.com/FuelLabs/sway/issues/2410 to keep track of it.  Feel free to update

**Comment by hal3e** [comment]
As we have fixed the parsing issue in the SDK, I  would suggest we close the PR and check the function after it gets fixed by the compiler team.

**Review by digorithm — APPROVED** [review]
Good stuff! 

Do you mind also creating an issue on `fuels-rs` for re-enabling the skipped test once the compiler issue is resolved?

**Comment by hal3e** [comment]
Thanks! I added the new issue (https://github.com/FuelLabs/fuels-rs/issues/509).

**Pull request merged**
