### PR TITLE
docs: migrate all examples

### LINKED ISSUE #342: docs: move *all* doc examples inside the `examples` directory
Even simple one-liners should be put inside the `examples/` directory so they can be tested by CI.

### PR DESCRIPTION
**Pull request by vnepveu**
This PR closes #342.
- All examples in `The Book` now use the `examples` directory. Some
  reorganization of that structure might/should happen down the road, but for
  now the idea is to just move forward with using only tested code in `The
  Book`.
  
Apologies in advance, this PR will probably be *hell* to review because there are snippets distributed everywhere lol :sweat_smile:

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Merge conflicts.

**Review by adlerjohn — COMMENTED** [review]
moar merge conflicts

**Review by Br1ght0ne — DISMISSED** [review]
Gave it my best, book LGTM.

**Review by adlerjohn — COMMENTED** [review]
CI failing. Looking good though.

**Review by adlerjohn — COMMENTED** [review]
Merge conflicts

**Comment by vnepveu** [comment]
> Merge conflicts
yeah we really need to merge this as soon as I fix them otherwise it's never going in haha

**Review by adlerjohn — APPROVED** [review]
utACK

**Pull request merged**
