### PR TITLE
chore!: Move `get_asset_outputs_for_amount`, `get_asset_inputs_for_amount` and `adjust_for_fee` from `Account` to `ViewOnlyAccount`

### PR DESCRIPTION
**Pull request by AurelienFT**
# Release notes

In this release, we:

- Move `get_asset_outputs_for_amount` and `adjust_for_fee` from `Account` to `ViewOnlyAccount`

# Summary

This PR moves `get_asset_outputs_for_amount`, `get_asset_inputs_for_amount` and `adjust_for_fee` from `Account` to `ViewOnlyAccount` trait. It seem that these two methods doesn't require a full `Account` and so it give more flexibility in order to implement them in other structures such as `Wallet`.

Now `Wallet` also implement these two methods. Before you were forced to build a `WalletUnlocked` even if you don't use the `secret_key`.

# Breaking changes

This contains an API breaking change as some public trait as been edited:

# Breaking Changes

The provider option flag `cacheUtxo` was renamed to `resourceCacheTTL`

```rust
// before
use fuels::acounts::Account;

wallet.get_asset_outputs_for_amount(...);
```

```rust
// after
use fuels::acounts::ViewOnlyAccount;

wallet.get_asset_outputs_for_amount(...);
```

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

**Review by Br1ght0ne — DISMISSED** [review]
LGTM, thanks!

**Comment by calldelegation** [comment]
@AurelienFT could you add the proper tag to the title, either chore, feat, or fix please? So the migration script can pick it upon the next release :)

Context: https://github.com/FuelLabs/fuels-rs/pull/1495

**Comment by AurelienFT** [comment]
> @AurelienFT could you add the proper tag to the title, either chore, feat, or fix please? So the migration script can pick it upon the next release :)

Done :)

**Comment by AurelienFT** [comment]
This PR is based on https://github.com/FuelLabs/fuels-rs/pull/1496

This PR can't be merged for now as it contains breaking changes and `master` do not accept new breaking changes for now.

**Comment by digorithm** [comment]
@AurelienFT Is this still a draft, or are we good to review it?

**Comment by AurelienFT** [comment]
> @AurelienFT Is this still a draft, or are we good to review it?

Yes sorry I placed it to draft to avoid merging before :p

**Review by Br1ght0ne — APPROVED** [review]

**Review by MujkicA — APPROVED** [review]
I've added a small change to docs, LGTM

**Pull request merged**
