### PR TITLE
bug: reexport lost fuels::tx::Output under fuels::types::output::Output

### PR DESCRIPTION
**Pull request by segfault-magnet**
We've recently lost our `fuels::tx::Output` reexport of the `fuel_tx::Output`, this PR introduces it back but under a less surprising location (`fuels::types::output::Output` to mimic the already existing `fuels::types::input::Input`)

Although I'm not a fan of the `output::Output` verbosity, I decided to leave it so that it doesn't surprise users. 

We should probably reexport the types under `fuels::types::{Input, Output}` rather than needlessly mention the internal mod structure.

### Checklist
- [x] I have linked to any relevant issues.
- [x] I have updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary labels.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by iqdecay — COMMENTED** [review]
Why not `fuels::types::{Input, Output}` directly? It would be released with the big changes from #950 anyway so it would make sense IMO.

**Comment by segfault-magnet** [comment]
> Why not `fuels::types::{Input, Output}` directly? It would be released with the big changes from #950 anyway so it would make sense IMO.

I'd love to, but then we'd have to also do all of these as well:
```rust
pub mod bech32;
pub mod block;
pub mod chain_info;
pub mod coin;
pub mod constants;
pub mod enum_variants;
pub mod errors;
pub mod input;
pub mod message;
pub mod message_proof;
pub mod node_info;
pub mod offsets;
pub mod param_types;
pub mod resource;
pub mod traits;
pub mod transaction;
pub mod transaction_builders;
pub mod transaction_response;
pub mod unresolved_bytes;
```

make them private mods and reexport their contents publicly. 

So I wanted to suggest the idea here before doing it. If the @FuelLabs/sdk-rust is ok with it lets do it.

**Comment by iqdecay** [comment]
Ah yes no ok this is much larger haha, warrants a discussion

**Comment by hal3e** [comment]
> > Why not `fuels::types::{Input, Output}` directly? It would be released with the big changes from #950 anyway so it would make sense IMO.
> 
> I'd love to, but then we'd have to also do all of these as well:
> 
> ```rust
> pub mod bech32;
> pub mod block;
> pub mod chain_info;
> pub mod coin;
> pub mod constants;
> pub mod enum_variants;
> pub mod errors;
> pub mod input;
> pub mod message;
> pub mod message_proof;
> pub mod node_info;
> pub mod offsets;
> pub mod param_types;
> pub mod resource;
> pub mod traits;
> pub mod transaction;
> pub mod transaction_builders;
> pub mod transaction_response;
> pub mod unresolved_bytes;
> ```
> 
> make them private mods and reexport their contents publicly.
> 
> So I wanted to suggest the idea here before doing it. If the @FuelLabs/sdk-rust is ok with it lets do it.

I like this idea. I suggest we do it in https://github.com/FuelLabs/fuels-rs/pull/956 as I am already introducing breaking changes there with re-exports.

**Review by hal3e — APPROVED** [review]

**Review by MujkicA — APPROVED** [review]

**Comment by iqdecay** [comment]
I think it's better if we separate those two issues, #956  is already big enought as it is.

**Pull request merged**
