### PR TITLE
Removed no-verify from publish crate

### PR DESCRIPTION
**Pull request by Dyltom**

### CODE REVIEW

**Comment by adlerjohn** [comment]
Thank you for the contribution. However, as #81 says, we need to wait for https://github.com/katyo/publish-crates/pull/394 to be merged first.

**Comment by Dyltom** [comment]
> Thank you for the contribution. However, as #81 says, we need to wait for [katyo/publish-crates#394](https://github.com/katyo/publish-crates/pull/394) to be merged first.

No worries, just thought I'd get it in early, and once https://github.com/katyo/publish-crates/pull/394 is merged, we can merge this one.

**Comment by adlerjohn** [comment]
Locking in that GitHub green 😂

**Review by adlerjohn — APPROVED** [review]
LGTM, but will defer to @digorithm

**Review by digorithm — APPROVED** [review]
LGTM -- Thank you for your contribution!

**Pull request merged**
