### PR TITLE
fix: use only base asset amount when calculating fee

### PR DESCRIPTION
**Pull request by mpoplavkov**
Resolves the issue https://github.com/FuelLabs/fuels-rs/issues/1239

### CODE REVIEW

**Review by digorithm — CHANGES_REQUESTED** [review]
Nice catch. The solution seems reasonable to me; can't think of anything wrong that this could lead up to, at the moment. 

The CI is failing because of a tiny formatting issue; make sure to `rustfmt` the code. 

Invoking some of the guys that worked on fees to double-check this solution: @MujkicA @hal3e @segfault-magnet

**Review by MujkicA — APPROVED** [review]
LGTM, thanks!

**Review by digorithm — APPROVED** [review]
Many thanks, @mpoplavkov! We'll cut a new release with this change asap.

**Comment by mpoplavkov** [comment]
Awesome, thanks!

**Review by Salka1988 — APPROVED** [review]

**Pull request merged**
