### PR TITLE
chore: use `beta-5` endpoint

### PR DESCRIPTION
**Pull request by iqdecay**
- No more transient CI errors!

### CODE REVIEW

**Review by hal3e — DISMISSED** [review]
LGTM

**Review by digorithm — COMMENTED** [review]
Nice. Let's hold this PR for a little bit until the beta-5 release is officially out; we don't want to accidentally release a new SDK version with these docs before people know about the beta-5.

**Review by MujkicA — COMMENTED** [review]
There is some more mentions of beta4 in the docs debugging section

**Comment by segfault-magnet** [comment]
Maybe to make it into a draft until things are ready? @digorithm @iqdecay

**Review by MujkicA — DISMISSED** [review]

**Review by Salka1988 — DISMISSED** [review]

**Review by hal3e — APPROVED** [review]

**Review by Salka1988 — APPROVED** [review]

**Review by MujkicA — APPROVED** [review]

**Pull request merged**
