### PR TITLE
add abigen to fuels Cargo.Toml

### PR DESCRIPTION
**Pull request by Salka1988**
I inserted `abigen!()` macro into the `fuel` library so users don't have to import the `fuels-core-abigen` library into Cargo.toml of their tests to use `abigen!()` macro.
From :

```rust
[project]
name = "zule"
version = "0.1.0"
authors = ["salka1988"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = "0.14"
fuels-abigen-macro = "0.14"
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
```
To:
```rust
[project]
name = "zule"
version = "0.1.0"
authors = ["salka1988"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = "0.14"
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
```
```

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
IIRC there was an issue with doing this, something to do with macros. @digorithm might remember.

**Comment by Voxelot** [comment]
We should also update the examples fuel-rs or any other test harnesses in the repo to use the new style of importing abigen from fuels.

**Comment by digorithm** [comment]
> IIRC there was an issue with doing this, something to do with macros. @digorithm might remember.

I remember hitting a problem while quickly trying to do this a while ago. But I _think_ it's possible now due to many refactors that we've been doing over the past months; especially the idea to re-export everything in a prelude, which wasn't a thing back then. 

So glad this can work now 😁

**Comment by adlerjohn** [comment]
Apparently all the tests pass, so...good? 😂

**Review by digorithm — APPROVED** [review]
This is such a nice QoL improvement -- great job!

This is a strong breaking change though, let's make sure the `forc` side is ready for this before releasing this.

**Comment by digorithm** [comment]
> Apparently all the tests pass, so...good? 😂

Yup, I also tested it with external Sway projects just now... it works! 🎉

**Review by Voxelot — DISMISSED** [review]

**Review by digorithm — APPROVED** [review]

**Pull request merged**
