### PR TITLE
Add `TxParameters` to transfer functionality

### PR DESCRIPTION
**Pull request by digorithm**
This PR introduces the addition of `TxParameters` to the `wallet.transfer()` API. Enabling the user to configure the `TxParameters` in a transfer call, which was previously hardcoded.

Now, transfers look like this:

```Rust
let receipts = wallet
            .transfer(&target.address(), amount, Default::default(), /* new */ TxParameters::default())
            .await
            .unwrap();
```

Also, I've moved `parameters.rs` from `fuels-contract` to `fuels-core`, to avoid a cyclic dependency problem now that `fuels-signers` need `parameters`, the same for `fuels-contract` needing `parameters`.

Closes https://github.com/FuelLabs/fuels-rs/issues/270.

### CODE REVIEW

**Review by Voxelot — COMMENTED** [review]
Should we have any tests that verify the tx params are set correctly on the tx?

**Comment by digorithm** [comment]
> Should we have any tests that verify the tx params are set correctly on the tx?

I think only if we tested `build_transfer_tx` https://github.com/FuelLabs/fuels-rs/blob/31b3111f8ff2e6cfe9094080a23854c1a183a40c/packages/fuels-signers/src/provider.rs#L109-L131

Because we can't see the tx inside transfer https://github.com/FuelLabs/fuels-rs/blob/31b3111f8ff2e6cfe9094080a23854c1a183a40c/packages/fuels-signers/src/wallet.rs#L144

And the call doesn't return the tx info.

But `build_transfer_tx` is so shallow that I don't see it being meaningful enough -- it only creates a `Transaction::Script`, it's super shallow. 

But I'm open to different testing strategies here though!

**Comment by Voxelot** [comment]
We could fetch the transaction back from the fuel-core API, essentially as a round-trip test to ensure fields set by the SDK are received and returned by the fuel-core service.

**Comment by digorithm** [comment]
I like the idea of fetching the tx from fuel-core API! Lemme see if I can get this done easily -- if it gets too tricky I'll leave it for a follow-up PR.

**Comment by digorithm** [comment]
@Voxelot Changed `transfer` a bit to return the tx id. Then I'm using that with the `fuel-core` API to get the tx and then asserting the params. Seems like a decent strategy! Changes here: https://github.com/FuelLabs/fuels-rs/pull/271/commits/33498c1503544ebe41af1dbbe28e5e760e7c3bcb.

**Comment by digorithm** [comment]
Yup, makes sense to me! Here it is: https://github.com/FuelLabs/fuels-rs/pull/271/commits/f264ddffe00411e1b2d263ac74f1f1b07f3860ea.

**Review by Voxelot — APPROVED** [review]

**Pull request merged**
